=head1 MYDLjE - Web-presence rethought

=head1 DESCRIPTION

B<NOTE: Everything below is just a TODO-list for now.>

MYDLjE is a lightweight Web-Applications and Content Management Framework.
It is a collection of Perl, JavaScript, CSS and HTML5 code libraries to form a General Purpose Platform for building Web-Applications.
We count on several "State Of the Art" open-source software projects to make a powerful platform for building business online.

The framework name is an acronym. It stands for: B<Mojolicious, YAML, DBI*, Locale::Maketext, jQuery, Elastic CSS> which are the main building blocks. B<Template::Alloy> is chosen as view system.

=head1 APPLICATIONS

MYDLjE comes with three bundled web applications around and on top of which you can build even more powerful domain specific applications. 
The applications are intended to be easy to use (intuitive) for the average computer-literate user.

=head2 CONTROL PANEL (cpanel)

This application is for managing your platform. You access and manage your users, customers, site, pages, content, applications etc.  
Only trusted people (back-end users) should be allowed to use it.

=head2 MYDLjE (mydlje)

This is a bare-bones application. It it is used as the base for the other two.

=head2 SITE (site)

This is your front-end application intended for the public. Build a site or a custom application to be used by your customers. 
Build whatever you want on top of and around it.



=head1 MINIMAL REQUIREMENTS

=over

=item * Perl 5.8.8

=item * Apache with mod_(f)cgi - if you deploy on a cheap, shared hosting.

=item * MySQL or DBD::SQLite Perl Module

=back

=head1 INSTALLATION

=over

=item 1 Unpack the bundle in a directory visible by Apache.

=item 1 Use your browser to access 
http://example.com/where/is/MYDLjE/index.html

=item 1 Follow the feather (our mascot).

=item 1 Enjoy your new site and start building your presence.

=back

=head1 ROADMAP

=over

=item 1 Implement the base system. Bundle required libraries and write enough tests to be sure the things work together well.

=item 1 Implement the "Control Panel" application

=over

=item 1 Implement the Users/Groups Management plugin;

=item 1 Implement the Screens/Pages Management plugin;

=item 1 Implement the Content Management plugin;

=item 1 Implement Applications/Plugins Management plugin;

=back

=item 1 Implement the "Site" application

=over

=item 1 Implement the "Registration" Site plugin;

=item 1 Implement the "Login" Site plugin(with Oauth2 and/or OpenID);

=item 1 Implement the "Profile" Site plugin

=item 1 Implement the "Q&A" Site plugin;


=back



=back

=head1 LICENSE and COPYRIGHT

This is a package of libraries written by many authors. 
Krasimir Berov bundled them together and wrote the domain specific parts
to form something that works as one. The code written by K. Berov 
is licenced under the LGPLv3. 
The other people's code is licenced under various 
Open Source Licences that allow redistribution and modifications.
See: http://www.perlfoundation.org/artistic_license_2_0, 
http://www.gnu.org/licenses/lgpl-3.0.txt

How to understand: http://www.perlfoundation.org/artistic_2_0_notes

(C) Krasimir Berov 2011

-----------------------

