=head1 MYDLjE - Web-presence rethought

=head1 DESCRIPTION

B<NOTE: Everything below is just a TODO-list for now.>

MYDLjE is a lightweight Web-Applications and Content Management Framework.
It is a collection of Perl, JavaScript, CSS and HTML5 code libraries to form a General Purpose Platform for building Web-Applications.
We count on several "State Of the Art" open-source software projects to make a powerful platform for building business online.

The framework name is an acronym. It stands for: B<Mojolicious, YAML, DBI*, Locale::Maketext, jQuery, Elastic CSS> which are the main building blocks. B<Template::Alloy> is chosen as view system. B<SILK & FLAG ICONS> are used too.

=head1 APPLICATIONS

MYDLjE comes with three bundled web applications around and on top of which you can build even more powerful domain specific applications. 
The applications are intended to be easy to use (intuitive) for the average computer-literate user.

=head2 CONTROL PANEL (cpanel)

This application is for managing your platform. You access and manage your users, customers, site, pages, content, applications etc.  
Only trusted people (back-end users) should be allowed to use it.

=head2 MYDLjE (mydlje)

This is a bare-bones application. It it is used as the base for the other two and for setting up the system for the first time when you unpack it where it iwill work.

=head2 SITE (site)

This is your front-end application intended for the public. Build a site or a custom application to be used by your customers. 
Build whatever you want on top of and around it.



=head1 MINIMAL REQUIREMENTS

=over

=item * Perl 5.8.8 or next;

=item * Apache with mod_cgi (standard) or (better/faster) mod_fcgi/mod_fastcgi;

=item * MySQL server, provided on every shared hosting;

=item * C<DBI>, C<DBD::mysql>, C<Time::Piece> and C<GD> Perl Modules.

=back


Almost all (even the cheapest) hosting providers meet the system requirements. 
To make sure, send the list to your (potential) hosting provider and ask them if they meet the requirements below. The setup screen also checks for the requirements. The system automatically runs under mod_fastcgi if available. See the .htaccess file.


=head1 INSTALLATION

=over

=item 1 Unpack the bundle in a directory visible by Apache.

=item 2 Use your browser to access B<index.xhtml> - see L</SETUP>.

=item 3 Follow the feather (our mascot).

=item 4 Enjoy your new site and start building your presence.

=back

=head1 ROADMAP

Below is the list of things to do. It is possible to work on several things at the same time so feel your self invited to help.

=over

=item 1 Implement the base system. Bundle required libraries and write enough tests to be sure the things work together well.

=item 2 Implement the MYDLjE initial setup/install.

=item 2 Implement the "Control Panel" application:

=over

=item 1 Implement the Configuration Management controller;

=item 2 Implement the Users/Groups Management controllers;

=item 3 Implement the Screens/Pages Management plugin;

=item 4 Implement the Content Management plugin;

=item 5 Implement Applications/Plugins Management plugin;

=back

=item 3 Implement the "Site" application:

=over

=item 1 Implement the "Registration" Site plugin;

=item 2 Implement the "Login" Site plugin(with Oauth2 and/or OpenID);

=item 3 Implement the "Profile" Site plugin;

=item 4 Implement the "Q&A" Site plugin;


=back



=back

=head1 LICENSES and COPYRIGHT

This is a package of libraries written by many authors. 
Krasimir Berov bundled them together and wrote the domain specific parts
to form something that works as one. The code written by K. Berov 
is licenced under the LGPLv3. 
The other works are licenced under various 
Open Source Licences that allow redistribution and modifications.
See: http://www.perlfoundation.org/artistic_license_2_0, 
http://www.gnu.org/licenses/lgpl-3.0.txt

How to understand: http://www.perlfoundation.org/artistic_2_0_notes

Copyright (C) 2008-2011, Krasimir Berov

=head1 CREDITS

I wish to thank to all who made something that I use to make MYDLjE works. 
If you think your name should be listed here, please notify me.

=over

=item * Larry Wall conceived Perl - http://www.perl.org/. Thank You!

=item * Sebastian Riedel makes Mojolicious - http://mojolicio.us/perldoc?Mojolicious . Thank You!

=item * YAML thanks to Oren Ben-Kiki, Clark Evans, Ingy döt Net - http://yaml.org/. Thank you all!

=item * Adam Kennedy makes YAML::Tiny - http://search.cpan.org/dist/YAML-Tiny/. Thank you!

=item * Paul Seamons makes Template::Alloy - http://search.cpan.org/dist/Template-Alloy/. Thank You!

=item * John Resig conceived jQuery - http://jquery.org/. Thank You!

=item * jQuery User Interface Team makes jQuery UI - http://jqueryui.com/about . Thank You!

=item * Sean M. Burke conceived Locale::Maketext - http://search.cpan.org/dist/Locale-Maketext/. Thank You! 

=item * Mark James made SILK & FLAG ICONS -  http://www.famfamfam.com/about/. Thank You!

=item * Fernando Trasvia conceived Elastic CSS - http://elasticss.com/suggestions/. Thank You!

=back

=head1 SETUP

=begin html

To begin setting up your system <a href="index.xhtml">go to index.xhtml</a>

=end html


-----------------------

