
=encoding utf8

=head1 MYDLjE Guides

Here is the place to start, no mater if you are a developer, admin or editor.

=head1 ADMINISTRATORS

The L<MYDLjE::Guides::Admins> guide is for those who manage one or several sites based on MYDLjE.
It is expected that you have general knowledge on how the I<World Wide Web> works and are familiar with notions like Apache, HTTP, FTP, XML, XHTML. Some knowledge of Perl and JavaScript is useful but not mandatory.

Thanks for using MYDLjE

=head1 DEVELOPERS

The L<MYDLjE::Guides::Devs> guide is for those who want to contribute to the project by 
implementing features and fixing bugs. Please read it before you contribute.

Thanks for joining.

=head1 EDITORS


=head1 SEE ALSO

L<MYDLjE>

=head1 AUTHOR AND COPYRIGHT

(c) 2011 Красимир Беров L<k.berov@gmail.com>

MYDLjE code is licensed under LGPLv3.


=begin html

<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Text" property="dct:title" rel="dct:type">MYDLjE::Guides</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://github.com/kberov/MYDLjE" property="cc:attributionName" rel="cc:attributionURL">Красимир Беров</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License</a>.<br />Based on a work at <a xmlns:dct="http://purl.org/dc/terms/" href="https://github.com/kberov/MYDLjE/blob/master/perl/lib/MYDLjE/Guides.pod" rel="dct:source">github.com</a>.

=end html

